version: '2'
services:
  quadra-app:
    image: quadra
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://quadra-postgresql:5432/quadra
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  quadra-postgresql:
    extends:
      file: postgresql.yml
      service: quadra-postgresql
